### ISSUE TITLE
helm starter list just lists the current directory

### ISSUE THREAD

**Issue by halkeye** [salesforce/helm-starter#1]
From looking at the code, it seems like HELM_PATH_STARTER is not set
I'm really not sure what is supposed to be setting it.

```
 ☎  ~  …  halkeye-helm-charts  %    helm starter list
+ PASSTHRU=()
+ [[ 1 -gt 0 ]]
+ key=list
+ case $key in
+ PASSTHRU+=("$1")
+ shift
+ [[ 0 -gt 0 ]]
+ set -- list
+ '[' '' == TRUE ']'
+ COMMAND=list
+ '[' list == fetch ']'
+ '[' list == list ']'
+ ls -A1
```

```
helm version
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

I'm sorta seeing it working if i use helm2, so if its not upgraded to support helm 3, i'd suggest writing something in the readme to say that.

**Comment by myspotontheweb** [comment]
This PR offers a fix for this issue

https://github.com/salesforce/helm-starter/pull/2

The [Helm FAQ](https://helm.sh/docs/faq/) describes how variables have changed between Versions 2 + 3

**Comment by rmichela** [comment]
Upgraded to Helm 3 in https://github.com/salesforce/helm-starter/commit/dac9a67bd56d5c3ccb9234e88e18a8d22f8d8bdb
